Working on pytest fixture
Current blocker: mypy
tests\conftest.py:28: error: Expression has type "Any"
    @pytest.fixture()
     ^

Also, added pytest to linting test in tox configuration so that pylint
would have access to importlib_metadata and pytest modules.